customhost = "database-1.ckefccseqn1g.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "wongzurong-employee"
customregion = "us-east-1"
